In [2]:
import pandas as pd
import numpy as np
import re

# Exercises

### 1. Write a function named is_vowel. It should accept a string as input and use a regular expression to determine if the passed string is a vowel. While not explicity mentioned in the lesson, you can treat the result of re.search as a boolean value that indicates whether or not the regular expression matches the given string.

In [10]:
regexp = r'[aeiou]'
subject = 'b'

result = re.match(regexp, subject)
print(result)

None


In [18]:
# writing the function:

def is_vowel(vowel):
    regexp = r'[aeiou]'
    subject = vowel

    result = re.findall(regexp, subject)
#     if result 
    return result, type(result)
    

In [20]:
is_vowel('a')

(['a'], list)

### 2. Write a function named is_valid_username

Function that accepts a string as input. A valid username starts with a lowercase letter, and only consists of lowercase letters, numbers, or the _ character. It should also be no longer than 32 characters. The function should return either True or False depending on whether the passed string is a valid username.

In [27]:
# goal is to force a result of None if string doesn't match parameters, and read the result if it does match the parameters. Then I can do True/False results in my function.

regexp = r'^[a-z]'
subject = 'a'

result = re.match(regexp, subject)
print(result)

<re.Match object; span=(0, 1), match='a'>


#### Plan:

The way I approached this (with Ryan's advice) was to break this function apart into several different subfunctions, and then from that point on roll the separate functions together into one.

In [144]:
def starts_lowercase(string):
    regexp = r'^[a-z]'
#     subject = string

    result = bool(re.match(regexp, string))
#     if result:
#         True
#     else:
#         False
    return result

In [145]:
def only_approved_char(string):
    return bool(re.search(r'^[a-z0-9_]+$', string))

In [146]:
def len_limit(string):
    return len(string) <= 32

In [147]:
def is_valid_username(string):
    return starts_lowercase(string) and only_approved_char(string) and len_limit(string)

In [148]:
is_valid_username('aluke123_texas2020')

True

### 3. Write a regular expression to capture phone numbers. It should match all of the following:

(210) 867 5309

+1 210.867.5309

867-5309

210-867-5309

In [154]:
regexp = r'[+-.()\d]'
subject = '(210) 867 5309 +1 210.867.5309 867-5309 210-867-5309'

result = re.findall(regexp, subject)
print(result)

['(', '2', '1', '0', ')', '8', '6', '7', '5', '3', '0', '9', '+', '1', '2', '1', '0', '.', '8', '6', '7', '.', '5', '3', '0', '9', '8', '6', '7', '-', '5', '3', '0', '9', '2', '1', '0', '-', '8', '6', '7', '-', '5', '3', '0', '9']


In [178]:
regexp = r'\d{3}-\d{3}-\d{4}'
subject = '(210) 867 5309 +1 210.867.5309 867-5309 210-867-5309'

result = re.findall(regexp, subject)
print(result)

['210-867-5309']


In [204]:
regexp = r'\d{3,}["."]\d{3,4}["."]\d{3,4}'
subject = '(210) 867 5309 +1 210.867.5309 867-5309 210-867-5309'

result = re.findall(regexp, subject)
print(result)

['210.867.5309']


In [238]:
regexp = r'(\d{3,})(-)'
subject = '(210) 867 5309 +1 210.867.5309 867-5309 210-867-5309'

result = re.findall(regexp, subject)
print(result)

[('867', '-'), ('210', '-'), ('867', '-')]


In [231]:
regexp = r'^(\d{3,})+$'
subject = '(210) 867 5309 +1 210.867.5309 867-5309 210-867-5309'

result = re.findall(regexp, subject)
print(result)

[]


In [251]:
regexp = r'(\d{,3}?\D+\d{3}\D+\d{4})'
subject = '(210) 867 5309 +1 210.867.5309 867-5309 210-867-5309'

result = re.findall(regexp, subject)
print(result)

['210) 867 5309', '210.867.5309', ' 867-5309', '210-867-5309']


In [260]:
regexp = r'(\(?\+?\d{,3}?\D+\d{3}\D+\d{4})'
subject = '(210) 867 5309 +1 210.867.5309 867-5309 210-867-5309'

result = re.findall(regexp, subject)
print(result)

['(210) 867 5309', '210.867.5309', ' 867-5309', '210-867-5309']


In [ ]:
# https://regex101.com/r/Ku2hLK/1

In [ ]:
(\(?\+?\d{,3}?\D+\d{3}\D+\d{4})

In [ ]:
\d{,3}?\D+\d{3}\D+\d{4}

In [264]:
# (\+1)|(\(?\d{,3}?\D+\d{3}\D+\d{4})

In [268]:
regexp = r'(\+1)|(\(?\d{,3}?\D+\d{3}\D+\d{4})'
subject = '(210) 867 5309 +1 210.867.5309 867-5309 210-867-5309'

result = re.findall(regexp, subject)
print(result)

[('', '(210) 867 5309'), ('+1', ''), ('', '210.867.5309'), ('', ' 867-5309'), ('', '210-867-5309')]


I'm going to break this done in my own words to make sure I understand it:

If this was my string of phone numbers: `'(210) 867 5309 +1 210.867.5309 867-5309 210-867-5309'`

Solution:
`(\+\d+)?\D*?(\d{3})?\D*?(\d{3})\D*?(\d{4})`

(\+\d+)? - This is the section that says, take the literal "+" sign, immediately followed by any 1 digit or more, but is optional because of the "?". That is encapsulated by () to make it a capture group. 

Then, using the \D* means: any 

In [ ]:
def phone_number(string):
    return bool()

In [ ]:
r'(/d3)/D+(/d3)/D+(/d4)'

In [270]:
# Zach's solution. I was approaching the question all wrong...

phone_number_re = re.compile(r'''
^
(?P<country_code>\+\d+)?
\D*?
(?P<area_code>\d{3})?
\D*?
(?P<exchange_code>\d{3})
\D*?
(?P<line_number>\d{4})
\D*
$
''', re.VERBOSE)

df = pd.DataFrame()
df['number'] = [
    '(210) 867 5309',
    '+1 210.867.5309',
    '867-5309',
    '210-867-5309',
]
pd.concat([df, df.number.str.extract(phone_number_re)], axis=1)

number country_code area_code exchange_code line_number
0   (210) 867 5309          NaN       210           867        5309
1  +1 210.867.5309           +1       210           867        5309
2         867-5309          NaN       NaN           867        5309
3     210-867-5309          NaN       210           867        5309

In [276]:
14-9

5

### 4. Use regular expressions to convert the dates below to the standardized year-month-day format.+

02/04/19

02/05/19

02/06/19

02/07/19

02/08/19

02/09/19

02/10/19

In [273]:
regexp = r'\d+[/]\d+[/]\d+'
subject = '02/04/19 02/05/19 02/06/19 02/07/19 02/08/19 02/09/19 02/10/19'

result = re.findall(regexp, subject)
print(result)

['02/04/19', '02/05/19', '02/06/19', '02/07/19', '02/08/19', '02/09/19', '02/10/19']


In [271]:
# Zach's solution:

regexp = r'(\d+)/(\d+)/(\d+)'
subject = '02/04/19 02/05/19 02/06/19 02/07/19 02/08/19 02/09/19 02/10/19'

result = re.findall(regexp, subject)
print(result)

[('02', '04', '19'), ('02', '05', '19'), ('02', '06', '19'), ('02', '07', '19'), ('02', '08', '19'), ('02', '09', '19'), ('02', '10', '19')]


### 5. Write a regex to extract the various parts of these logfile lines:
GET /api/v1/sales?page=86 [16/Apr/2019:193452+0000] HTTP/1.1 {200} 510348 "python-requests/2.21.0" 97.105.19.58

POST /users_accounts/file-upload [16/Apr/2019:193452+0000] HTTP/1.1 {201} 42 "User-Agent: Mozilla/5.0 (X11; Fedora; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36" 97.105.19.58

GET /api/v1/items?page=3 [16/Apr/2019:193453+0000] HTTP/1.1 {429} 3561 "python-requests/2.21.0" 97.105.19.58

In [ ]:
# \s(?=(?:[^"]*"[^"]*")*[^"]*$)(?![^\[]*\])

### 6. You can find a list of words on your mac at /usr/share/dict/words. Use this file to answer the following questions:

- How many words have at least 3 vowels?
- How many words have at least 3 vowels in a row?
- How many words have at least 4 consonants in a row?
- How many words start and end with the same letter?
- How many words start and end with a vowel?
- How many words contain the same letter 3 times in a row?
- What other interesting patterns in words can you find?